# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - github-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_196ff2f0494a4a10bb53ed4bee98dc1a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3aefb75b33cb4cb99ef4eef7e4255a9c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_196ff2f0494a4a10bb53ed4bee98dc1a }}/birklauritzen/github_microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'github-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d9442d6714534532b30cc429b65fd3b5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_196ff2f0494a4a10bb53ed4bee98dc1a }}/birklauritzen/github_microservice:${{ github.sha }}'