# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - githubservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_053a487152ff4c49a5a3077b2b8c25bf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61cc04039a3141b684892342b3970c59 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_053a487152ff4c49a5a3077b2b8c25bf }}/github_microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'githubservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eab50f18e56441d789099f1525783d42 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_053a487152ff4c49a5a3077b2b8c25bf }}/github_microservice:${{ github.sha }}'