name: Build and deploy container app to Azure Web App - github-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_a709ce38f42746eca69279a7a3f98809 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb4886b6f9ff413f89724d2e09466f70 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_a709ce38f42746eca69279a7a3f98809 }}/github_microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'github-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f14746339f349169a1b0ad5b37c1323 }}
        images: ${{ secrets.AzureAppService_ContainerUsername_a709ce38f42746eca69279a7a3f98809 }}/github_microservice:${{ github.sha }}
